### ISSUE TITLE
Extending example with imports

### ISSUE THREAD

**Issue by atecce** [OfficeDev/Excel-Add-In-TS-Start#4]
When attempting to use this example as a springboard to prototype, `import`s are compiled down to `require` statements, which are not supported and throw the error

`require is undefined`

In addition, before you even get to this point an `Objects.defineProperty(exports, "__esModule", { value: true });` is generated and throws an error `exports is undefine`

How should one attempt to extend this example by importing external libraries (for this particular use `web-grpc` stubs)?

**Comment by Rick-Kirkham** [comment]
@atecce Could you provide some more detail? This project has only one TypeScript file and it does not have any `import `statements.
If you have created your own project that does use `import` statements in the TypeScript, then I think you need to install a library into the project that defines require. (Maybe commonjs or require.js. I'm not sure.) At any rate, if your problem is not with this sample, as it is, then you should raise it on StackOverflow and tag it "office-js". That way the whole community will benefit from the answers you get.

**Comment by atecce** [comment]
Right, the assumption I suppose was that this example could be used as a starter project that you can _extend_, and not just a sealed singleton.

Thanks!
